### ISSUE TITLE
Incompatibility with serverless CI/CD service

### ISSUE THREAD

**Issue by fedeiglesias** [fernando-mc/serverless-finch#100]
Compat with serverless CI/CD service

Serverless CI/CD run 3 commands
- npm install
- npm run test
- serverless deploy

We **[cannot change this commands, but we can create hooks](https://serverless.com/framework/docs/dashboard/cicd/custom-scripts/)** before and after each one adding `preinstall`, `postinstall`, `pretest `and `posttest `custom scripts to package.json. Also using serverless-plugin-scripts we can add hooks before and after deploy.

### Current behavior (if any)

When we add `serverless client deploy --no-confirm` command after-deploy hook, the serverless virtual machine do not implement the autenthification setted in the dashboard and we get this error:

> ServerlessError: AWS provider credentials not found. Learn how to set up AWS provider credentials in our docs here: <http://slss.io/aws-creds-setup>.

### Proposed behavior
Run the pipeline in Serverless CI/CD service using plain `serverless deploy` command. (without `client`)

**Comment by fernando-mc** [comment]
Thanks for submitting this @fedeiglesias! I'll look into how the credentials are made accessible there and get back to you on how this gets implemented.

**Comment by fernando-mc** [comment]
@fedeiglesias I'm not able to reproduce this? I'm testing with this service here: 
https://github.com/fernando-mc/serverless-frontend-backend

I have a connected AWS account using Deployment Profiles. Can you share more details of your configuration with me? You're welcome to DM me in the Serverless Slack: serverless.com/slack

My ID is `UMZ8N7ZRQ` (There are multiple imposters all claiming to be the real "Fernando"!)

**Comment by fedeiglesias** [comment]
@fernando-mc  i tried to fork from your repo but serverles CI/CD give this error:

**Choose a repo with at least one serverless.yml in it.**

I dont know why... i tried modifiying the serverless.yml file but i cannot make it run.
So, i create a clean repo in github using the same config as yours and this time serverless dash dont give me the error. 

[https://github.com/fedeiglesias/serverless-finch-cicd](https://github.com/fedeiglesias/serverless-finch-cicd)

Then i make this steps:

1. enter to https://dashboard.serverless.com/
2. Click '**add app**' button
3. Enter some name & click '**add app**'
4. Click '**add a service**' in your just created app
5. Go to '**app settings**' tab, Click '**stages**' in left menu.
6. Click '**add stage**' in name field tipe 'dev' and click '**save**' button
7. Go to '**ci/cd settings**' tab, and select the repo to build from.
8. If you do not see your repository listed, install the Serverless application in Github.
9. For basic setup, leave all options as default an click '**save settings**'

Now the app is created and linked to Github repo.

To deploy to AWS we can:
1. Click '**deploy service**' manually
2. Push some change to master branch in repo

(To deploy manually go to '**services**' tab and click in '**deploy service**')

After all:
The problem is still the same, maybe im doing some step wrong. 
In my opinion serverless CI/CD only run `serverless deploy` with permissions and the 'derived' commands runned as hooks dont have the permissions setted in the dashboard.
Im newbee with the framework and i think the most probably is that im doing wrong.


**### Here the log from serverless CI/CD**
`build step: npm install

serverless-finch-cicd@0.1.0 postinstall /serverless-finch-cicd
serverless client deploy --no-confirm

Serverless: This deployment will:
Serverless: - Upload all files from 'client/dist' to bucket 'serverless-finch-cicd'
Serverless: - Set (and overwrite) bucket 'serverless-finch-cicd' configuration
Serverless: - Set (and overwrite) bucket 'serverless-finch-cicd' bucket policy
Serverless: - Set (and overwrite) bucket 'serverless-finch-cicd' CORS policy
Serverless: Looking for bucket...
 
  Serverless Error ---------------------------------------
 
  ServerlessError: AWS provider credentials not found. Learn how to set up AWS provider credentials in our docs here: <http://slss.io/aws-creds-setup>.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              10.13.0
     Framework Version:         1.63.0
     Plugin Version:            3.4.0-a6edbce1
     SDK Version:               2.2.1-11-g1c9f7eb
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
 
npm
 ERR! code ELIFECYCLE
npm
 ERR! errno 1
npm
 ERR! serverless-finch-cicd@0.1.0 postinstall: `serverless client deploy --no-confirm`
npm ERR!
 Exit status 1
npm ERR! 
npm ERR! Failed at the serverless-finch-cicd@0.1.0 postinstall script.
npm ERR!
 This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-15T10_55_01_967Z-debug.log
build step failed: npm install
failure
Deploy failed!
Error: Build step failed: npm install`

**Comment by fernando-mc** [comment]
@fedeiglesias Two things here - first, the reason that you might have had issues with the fork is that I think the CI/CD doesn't really support CI/CD of forks at the moment. If you change it to an unforked repo you should be able to get it setup.

The second part relating to the credentials is that I would expect you to have a [profile](https://serverless.com/framework/docs/dashboard/profiles/ ) setup along with an `app` and `org` value in `serverless.yml`. 

Do you have those things already done? That's the critical step here as it needs a profile related to the application stage in order to deploy the service *or* to deploy the frontend.

**Comment by fedeiglesias** [comment]
@fernando-mc  as you said, there was `app `and `org` value in `serverless.yml`.
Thank you for your big help!!!
