### ISSUE TITLE
Serverless command "client" not found

### ISSUE THREAD

**Issue by Kinfol** [fernando-mc/serverless-finch#106]
I am running the command serverless client deploy --region us-west-2

I get. 

Serverless command "client" not found

**Comment by StephaneP** [comment]
did you install the plugin and then add finch in your serverless.yml plugins section? if not thats the problem

**Comment by fernando-mc** [comment]
Thanks for jumping in here @StephaneP! That is exactly what I would have suggested and most likely should solve the issue. Closing this for now but @Kinfol feel free to reopen if it doesn't fix the issue.
