### ISSUE TITLE
Could not find '/service-name/build' folder in your project root

### ISSUE THREAD

**Issue by lionheart2013** [fernando-mc/serverless-finch#108]
This is a:

* [] Feature request or change
* [x] Bug report

---

For bug reports:

### Expected behavior
remove stack created via Preview Deployment(CICD) upon branch deletion.
### Actual behavior
removed Failed: Could not find '/service-name/build' folder in your project root
### Steps to reproduce

* **Operating system:**
* **serverless-finch version:**
2.6.0
* `serverless.yml` **that produces bug:**
<pre>
custom:
  client:
    bucketName: service-name-my-bucket
    distributionFolder: ./build
</pre>
* **Command that produces bug:**
* **Other details:**

---

For feature requests or changes:

**Comment by fernando-mc** [comment]
It sounds like you're having an issue with the framework itself or the serverless.com features but not with this plugin? 

"Remove stack created via Preview Deployment(CICD) upon branch deletion."

This plugin doesn't touch CloudFormation so there would be no issue relating to CloudFormation Stacks. I would suggest opening an issue here: https://github.com/serverless/serverless

Let me know if I misunderstood but this plugin will deploy your `./build` folder when running `serverless client deploy`.

I can't help much with preview deployments as that's a feature of the serverless.com tooling.

If I'm incorrect here, please feel free to reopen it.

**Comment by lionheart2013** [comment]
@fernando-mc , thanks man appreciate your response on this and yes I think you are correct, already contacted serverless.com support team for the issue.
