### ISSUE TITLE
Print static website url upon completion

### ISSUE THREAD

**Issue by dmk255** [fernando-mc/serverless-finch#11]
It would be nice to be able to have the amazon generated static website url generated upon completion.

e.g.

`http://<bucket-name>.s3-website-<region>.amazonaws.com/`

**Comment by fernando-mc** [comment]
@dmk255 I think this is a great suggestion. There's a PR open for how we can do this correctly - https://github.com/fernando-mc/serverless-finch/pull/6

Feel free to put your thoughts there.

**Comment by amsross** [comment]
I opened #13 to address the correctness of #6 as well as this issue (which brought me here).

**Comment by fernando-mc** [comment]
@amsross and @dmk255 v1.3 is published which outputs the static website endpoint. 

Be aware that this is not always:
`http://<bucket-name>.s3-website-<region>.amazonaws.com/`

Sometimes it is:
`http://<bucket-name>.s3-website.<region>.amazonaws.com/`

We are now logging the correct url for each file deployed.
