### ISSUE TITLE
Exempt certain files from upload? / Exempt .DS_Store by default?

### ISSUE THREAD

**Issue by ScottyMJacobson** [fernando-mc/serverless-finch#111]
This is a:

* [x] Feature request or change
* [] Bug report

### Current behavior (if any)

`serverless-finch` uploads every file in the `distributionFolder`, including undesirable files (specifically .DS_Store)

### Proposed behavior

Allow an `include` and `exclude` option like serverless does in its [Packaging](https://www.serverless.com/framework/docs/providers/aws/guide/packaging) functionality. OR - use the same defaults! Which includes ignoring .DS_Store files.

### Justification

I don't know that uploading `.DS_Store` constitutes a major security threat, but it certainly isn't security best practice, and it'd be great to avoid accidentally uploading them.

Thank you!
Scotty

**Comment by benheymink** [comment]
Dupe of https://github.com/fernando-mc/serverless-finch/issues/70

**Comment by ScottyMJacobson** [comment]
Ah, thank you for pointing out the duplicate! (did a search and tried to see if it existed, but no dice)

High level implementation strategy - add an `ignoreFiles` argument to the options that takes in an array of globs, pass it to `uploadDirectory`, and on line 25 `allFiles` would become `allEligibleFiles` or something

TBD how much trouble I'd have writing a test case for it; haven't looked at your test framework yet

**Comment by fernando-mc** [comment]
@benheymink Thanks for pointing this out as a dupe!

@ScottyMJacobson appreciate the feedback! I think it's a good feature request. I'll close this and we can address this in #70

You're welcome to add the recommendations there and I'd love to see a PR to support this functionality.

Unfortunately, the testing strategy is very poor right now. I'd also be open to any PRs that improve that process.
