### ISSUE TITLE
Using KeyPrefix does not delete the s3 bucket after "sls remove" command.

### ISSUE THREAD

**Issue by thescientist23** [fernando-mc/serverless-finch#134]
This is a:

* [] Feature request or change
* [x] Bug report

---

For bug reports:

### Expected behavior
"sls remove" should remove the bucket
### Actual behavior
objects was deleted but the bucket remains, although it is empty but in a long run it will pile up on my aws account.
### Steps to reproduce
Added KeyPrefix to yml file.
<pre>
custom:
   client:
     keyPrefix: 'samplepref'
</pre>
Below is the result of "remove" command.
<img width="411" alt="Screen Shot 2022-01-18 at 3 33 34 PM" src="https://user-images.githubusercontent.com/11047543/149892217-ae750361-f28b-4c60-8ec0-ed1b7cc1e117.png">

I think this block of code has something to do with the behavior.
<img width="842" alt="Screen Shot 2022-01-18 at 3 38 11 PM" src="https://user-images.githubusercontent.com/11047543/149892333-e3393a19-7ff9-43e1-beaf-c58a38439fbc.png">

* **Operating system:*osx*
* **serverless-finch version:*2.8.0*
* `serverless.yml` **that produces bug:**
* **Command that produces bug:**
* **Other details:**

---

For feature requests or changes:

**Comment by mikejpeters** [comment]
On one hand I think it makes sense not to remove the bucket when `keyPrefix` is being used, since ait could be used used when deploying to a bucket that also contains other data. But there may be other use cases, such as making the deployment match the naming conventions of frontend frameworks / tools.

@thescientist23 if you're still interested in this functionality can you please explain why you're using `keyPrefix` but also want the bucket removed?

I think if we want to support removing the bucket when `keyPrefix` is in use it should be using a new option.

**Comment by fernando-mc** [comment]
@mikejpeters seconding what you're saying here. This could have unintended consequences that I'm not comfortable with. If we add support for this it should be in a new feature/setting.

**Comment by thescientist23** [comment]
@mikejpeters , thanks for your response, I am using `KeyPrefix` for my custom domain, basically for developing feature branch, eg. `https://domain.com/feat-1`, `https://domain.com/feat-2`,...etc. and to map the location according to feature branch I am deploying the react app on non root path thats where the `KeyPrefix` came into play.

**Comment by mikejpeters** [comment]
Thanks for the response. I'm assuming you wouldn't want this plugin to delete the bucket if there are still other objects i (e.g. in your case feature branches)?

@fernando-mc can you weigh in on this again when you have a chance? If the plugin deletes the objects at the prefix, and then only deletes the bucket **if it's completely empty** I don't see a downside. But maybe I'm missing some danger / use case? Having a new option like "force remove bucket" is safer but IMO less user-friendly. I like having smart defaults / less options, even if it means releasing a new major version with breaking changes

**Comment by fernando-mc** [comment]
@mikejpeters - I also prefer clean sensible defaults so as long as we release this with a major version bump I'm fine with it. I agree it probably makes sense and there's aren't many people who would object to it but it does change default behavior destructively and there's always some weird use cases we can't predict.

When including this:
1. Add a warning to release notes
2. Bump a major version

Then we're covering our bases and should be fine.
