### ISSUE TITLE
MAINTEINERS NEEDED

### ISSUE THREAD

**Issue by fernando-mc** [fernando-mc/serverless-finch#142]
Hello friends.

It's been ~5 years and I am no longer able to do active maintenance on this package.

I am looking for maintainers who are able to help contribute patches and review PRs or an organization I can entrust the NPM repository to. 

My best,
Fernando

**Comment by martinhalford** [comment]
Hi @fernando-mc, we might be about to help. We use Serverless-Finch in our project and it would be great to see it continue.

**Comment by fernando-mc** [comment]
@martinhalford thanks for reaching out! Can you email me so we can set up a short call to talk about it? I'm open to anything from adding core maintainers who can take ownership to full ownership by a reputable org.

My contact info:
https://www.fernandomc.com/contact/

**Comment by Shereef** [comment]
I can also help by reviewing PRs and testing. I don't know if the company I work for would be willing to take ownership but I can ask.

**Comment by fernando-mc** [comment]
Thanks @Shereef! I'm making a short list of folks just to act as more dedicated maintainers. Happy to add you if you're interested!

**Comment by fernando-mc** [comment]
@Shereef can you reach out to me via email? I'll add you to a maintainer thread with @martinhalford and @mikejpeters

@linusmarco you want on there too? I know it's been a while so I understand if you're busy with other things!
