### ISSUE TITLE
AWS Credentials for integration tests

### ISSUE THREAD

**Issue by Shereef** [fernando-mc/serverless-finch#145]
This is an issue to discuss having AWS Creds in the github repo.

For feature requests or changes:

### Current behavior (if any)
Integration tests fail https://github.com/fernando-mc/serverless-finch/runs/5343253800?check_suite_focus=true

### Proposed behavior
Added AWS Credentials to be able to run integration tests successfully
### Proposed implementation details (optional)
- @fernando-mc is hardening the credentials down so they can only perform the minimal actions needed to run the integration tests
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowAllAccessToFinchTest",
            "Effect": "Allow",
            "Action": "s3:*",
            "Resource": "arn:aws:s3:::serverless-finch-test-*"
        },
        {
            "Sid": "RequiredByServerless",
            "Effect": "Allow",
            "Action": "s3:ListAllMyBuckets",
            "Resource": "*"
        }
    ]
}
```

1. Add new Policy to AWS
2. Add a new user to IAM with only programatic access and note the Key ID and Key Secret
3. Assign the new policy to the IAM User
4. Added the keys to [this page](https://github.com/fernando-mc/serverless-finch/settings/secrets/actions) and add them

### Justification
Testing incoming changes

**Comment by Shereef** [comment]
@fernando-mc I have done some research on your behalf and included the steps above

I don't like that you need to have `s3:ListAllMyBuckets` on there but serverless tries to list all buckets and if it doesn't have the permission it doesn't try to bypass the error so it must be added

**Comment by fernando-mc** [comment]
Though @Shereef will this work for @mikejpeters's PR? I thought we were making buckets of the account ID?

**Comment by Shereef** [comment]
The * makes it work `"Resource": "arn:aws:s3:::serverless-finch-test-*"` I will test it

**Comment by fernando-mc** [comment]
Works for me, I thought the start of bucket resources was the account ID didn't realize we prefixed with serverless-finch-test but makes sense to me! Integration tests seem to be running well @mikejpeters. 

Feel free to merge whenever two maintainers approve. You should have credentials needed to make a release. Please make sure to update docs before that and make sure that this is a new major version for the release to help avoid any issues for folks relying on this and wanting to avoid potential breaking changes we might make supporting framework v3.

**Comment by fernando-mc** [comment]
You're good on this release. Just sync with @mikejpeters at some point to figure out who is writing release notes/doc updates. As long as you don't introduce anything else major consider it a sign off from me @Shereef! I'm out for several hours now but will be back on tonight if you need anything.
