### ISSUE TITLE
Fully automate releases

### ISSUE THREAD

**Issue by mikejpeters** [fernando-mc/serverless-finch#146]
### Current behavior

I think releases are currently done as follows:

1. Update the version in `package.json`
2. Add changelog to the readme
3. Push to master
4. Create a GitHub release which triggers the npm publish workflow.

### Proposed behavior

Use [semantic-release](https://github.com/semantic-release/semantic-release) to fully automate releases so the process is as simple as running a GitHub action.

**IMPORANT: This relies on using something like [Angular Commit Message Conventions](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-format) when writing commit messages.** I want to make sure everyone involved is on board with this before I write a PR for this. I would add documentation as well as commit linting to help us remember to keep the commit messages in the correct format.

I've done this on other projects and it works great.

### Justification

Save time, improve consistency, and simplify collaboration

**Comment by mikejpeters** [comment]
@fernando-mc @Shereef this is not high priority, but whenever you have time can you let me know if this is something that you'd be interested in? It's not a lot of work for me to implement. Please @ mention anyone else who should be involved in this decision as well.

(And if there's a better way to make these suggestions or have these conversations please let me know)

Thanks!

**Comment by Shereef** [comment]
I like it
That's what I understood from your other PR.

The linting part is new and I agree with it.

**Comment by Shereef** [comment]
I prefer the manual action since we need to coordinate and approve
eachother releases

> Message ID: ***@***.***
> com>
>
ᐧ

**Comment by fernando-mc** [comment]
@mikejpeters totally fine with doing this. The NPM token should be in the repo to make this possible. 

Ideally we don't do this immediately off of merges to master - only when we cut a new release though. We'll want to let tests run, write up release notes etc. and then have sign off before we do releases. 

But if you want to trigger it off of releases I think we can do that. I have another repo that does that here if you want to look at the GitHub workflow (that is if you haven't already implemented this in a new PR somewhere!) :
https://github.com/fernando-mc/aws-mailman/blob/master/.github/workflows/python-publish.yml

**Comment by mikejpeters** [comment]
Ok sounds good, let's trigger it manually. I will write up a PR soon to do this.  The semantic-release can actually generate the GitHub release automatically using the commit messages, which IMO is great because it saves a lot of time there (and you can still edit the notes after if necessary)
