### ISSUE TITLE
Enable `Automatically delete head branches` in the repo settings

### ISSUE THREAD

**Issue by Shereef** [fernando-mc/serverless-finch#151]
This is a:

* [✓] Change

---

For feature requests or changes:

### Current behavior (if any)
- Branches have to be deleted manually
### Proposed behavior
- Branches get deleted automatically when merged
### Proposed implementation details (optional)
1. Click settings
2. Check the box `Automatically delete head branches`
### Justification
One less thing we have to do manually

**Comment by fernando-mc** [comment]
<img width="863" alt="Screen Shot 2022-02-27 at 10 29 48 AM" src="https://user-images.githubusercontent.com/6182464/155894966-ee7e2db6-c801-4af7-b205-9426d14ccb7a.png">

Done. Thanks for the issue @Shereef
