### ISSUE TITLE
Approval Requirements - RFC

### ISSUE THREAD

**Issue by fernando-mc** [fernando-mc/serverless-finch#152]
Just added these requirements. Open to changing them as needed. 

@mikejpeters this is what I should have put into place earlier to avoid accidental merges. 

<img width="1188" alt="Screen Shot 2022-02-27 at 10 27 22 AM" src="https://user-images.githubusercontent.com/6182464/155894898-69cafc90-9d0a-47fb-b164-d891aeb144b4.png">

cc @Shereef 

Let me know if these look okay to you both.

**Comment by Shereef** [comment]
Thanks so much for this!
<img width="763" alt="image" src="https://user-images.githubusercontent.com/356763/155896190-e2671888-4dd6-4a1f-b9d8-965ffb4ec520.png">
Those would be nice also to have tests required 

<img width="746" alt="image" src="https://user-images.githubusercontent.com/356763/155896220-e874714c-b679-42c6-ac5b-02462970e712.png">
This one is also nice 


I noticed the only merge commits are the ones I added so maybe this one too 
<img width="491" alt="image" src="https://user-images.githubusercontent.com/356763/155896244-0d732f33-95db-4381-b621-38a5333e3c8d.png">

I shouldn't be allowed to 😆

**Comment by fernando-mc** [comment]
Updated:
<img width="804" alt="Screen Shot 2022-02-27 at 12 48 10 PM" src="https://user-images.githubusercontent.com/6182464/155899327-649a5c7a-d006-43f4-8544-573126c545fb.png">

**Comment by fernando-mc** [comment]
Not sure how GitHub pulls the status check names in. @mikejpeters might be worth checking this because I couldn't find "Integration" tests so maybe it pulls the name directly from the name within the yaml not the filename.

**Comment by Shereef** [comment]
It won't show because integration is not marked to ru non PRs
Regards,

<https://daysmart.com/>

*Shereef Marzouk*

Team Lead Full Stack Engineer

M: 902.299.5590

DaySmart Software

3520 Green Court, Suite 250

Ann Arbor, MI 48105



ᐧ

**Comment by mikejpeters** [comment]
Seems like what Shereef made sense, it wouldn't be possible to enforce integration tests unless we enable them to run on pull requests as well.

Requirements look good to me

**Comment by fernando-mc** [comment]
Ahh got it, makes sense. Well then keep me posted if I need to make other changes from the above. Closing this for now.
