### ISSUE TITLE
v4

### ISSUE THREAD

**Issue by mikejpeters** [fernando-mc/serverless-finch#162]
I'd like to keep momentum going and create a new release soon.

It may be a while before we come up with better CORS defaults (#159), but now we've merged #160 for custom CORS config file, and hopefully merge a small fix in #161 shortly.

NOTE: the release process is now automated which means it's just triggering a GitHub action. We agreed to do releases with approval, so I'm hoping I can get informal approval here from either @Shereef or @fernando-mc.  Assuming everything goes well, the release will automatically be a new major version and will include a note about the breaking changes in #158. If anything goes wrong I will work on fixing that action.

**Comment by Shereef** [comment]
@mikejpeters Do we need to do release notes ? iirc you said that would be automated right ?

**Comment by Shereef** [comment]
I would think we'd either need to add release notes manually to the ReadMe.md or remove them and link to somewhere else where they will be generated
Please make a PR titled v4 with those changes and I will approve that

**Comment by mikejpeters** [comment]
The release notes are automatically added to the release. I think that's been done manually in the last releases anyway. I think we should remove the existing ones from the readme at some point and just link to releases if you think it won't be obvious

**Comment by mikejpeters** [comment]
I think part of the idea of conventional commits is you're kind of approving the release notes at the same time as you approve each PR. Then the release is nice and easy :)
