### ISSUE TITLE
Feature suggestion: Allow user to set redirect options for the bucket

### ISSUE THREAD

**Issue by linusmarco** [fernando-mc/serverless-finch#21]
Now that the plugin allows for custom index and error documents ( #20 ), I think the next logical step on that path would be to allow users to specify the other two website configuration options: `RedirectAllRequestsTo` and `RoutingRules` ([docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-websiteconfiguration.html#cfn-s3-websiteconfiguration-redirectallrequeststo)). Personally, I use routing/redirect rules on occasion, so it would be great to have the option to do this via the plugin (especially because these options get reset upon deploy currently). 

I'd be happy to submit a PR for this if it's something that you think you'd want to include.

**Comment by fernando-mc** [comment]
@linusmarco I have to think on this one a little. One thing I want to eventually move this plugin towards is handing custom domains, CloudFront distributions, and SSL certs.

I'm generally open to ideas that don't interfere with the default behavior. But I've not used those specific config options before. I'm assuming that they wouldn't really get in the way of that sort of functionality if they we're optional right?

If so, go for it on the PR front. I will warn you that I've been horribly truant on reviewing, testing, and approving PRs but I'm hoping to get a better release cycle soon.

**Comment by linusmarco** [comment]
Okay, sounds good. Thanks for the feedback, @fernando-mc. These options shouldn't get in the way of any already-existing functionality. I'll work on it and submit a PR. No worries if takes a while to approve. The direction you're heading sounds awesome--that would be very useful. I'll be happy to pitch in with other contributions going forward.

**Comment by fernando-mc** [comment]
Sounds great @linusmarco ! Honestly, the toughest part for me right now has been testing to make sure new PRs don't break existing functionality. If you have suggestions to streamline that I'd love your thoughts. 

Don't get me wrong though, any PRs for new functionality will be very much appreciated!

**Comment by fernando-mc** [comment]
This is related to one of the PRs I think I dropped the ball on. Assigning back to you to peek over after we merge/publish v2.

**Comment by linusmarco** [comment]
You didn't drop the ball at all--this was actually addressed in the refactor (#43) :smiley:. I'll close this issue
