### ISSUE TITLE
Add linting

### ISSUE THREAD

**Issue by linusmarco** [fernando-mc/serverless-finch#32]
@amsross suggested that we add linting for standardization and to avoid having to catch/point that stuff out in PR review. I'm a big fan of [prettier](https://prettier.io/) because it will both lint the code and can be set up to auto-format everything via editor plugins.

Here's my proposed setup:

package.json
```json
...
"scripts": {
    "format": "prettier --write '**/*.js'",
    "pretest": "prettier --list-different '**/*.js'",
    "test": "mocha"
  },
...
```

This will lint and throw errors when `npm test` runs (locally or via CI). I also added a `format` script as a convenience so that contributors can clean up their code via the command prompt if they don't have prettier set up in their editor.

In terms of style choices, I think prettier's defaults take care of most of it, but here are my suggested settings (totally open to disagreement--just want to throw something out there):

.pretterrc
```json
{
    "printWidth": 100, // overrides default of 80
    "singleQuote": true // prefers single quotes unless string contains single quotes
}
```

@amsross, @fernando-mc,  any thoughts? I have a PR ready to put in with this if you're all okay with these settings.

**Comment by fernando-mc** [comment]
@linusmarco Works for me. We'll probably need to update the repo itself to conform. I'm sure it has some style violations already.

Can we do this as a pre-commit hook? https://prettier.io/docs/en/precommit.html

Or do you prefer a Travis CI integration?

Alternatively, we can create a PR template to ask folks to lint their own code? https://blog.github.com/2016-02-17-issue-and-pull-request-templates/

**Comment by linusmarco** [comment]
@fernando-mc - yup the existing codebase will definitely need to be updated to conform. I would plan to just update it as part of the PR that adds the linting.

Pre-commit linting is a great ideaI I got it working locally and will submit a PR now.
