### ISSUE TITLE
Writing unit and integration tests

### ISSUE THREAD

**Issue by linusmarco** [fernando-mc/serverless-finch#34]
(split out from #29)

Let's try to get complete coverage of the code we have to help make sure that everything works as expected now and going forward as new functionality is added.

@fernando-mc, I can lead this charge.

If anyone has ideas for specific tests that we should include, please chime in here.

**Comment by fernando-mc** [comment]
Also putting this here - This project has some cool tests that I think we can think about learning from too:
https://github.com/stojanovic/scottyjs

**Comment by fernando-mc** [comment]
@linusmarco Leaving this assigned to you since you claimed it.

**Comment by fernando-mc** [comment]
I think we can close this for now given work @mikejpeters did today!
