### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by mebibou** [fernando-mc/serverless-finch#4]
I'm a little bit confused on how to use this, after I added the module using `npm install serverless-finch --save-dev`, if I run `serverless client ...` there is no way this would work as there is no `bin`. How are we supposed to use this? the README is not clear enough imho

**Comment by fernando-mc** [comment]
@mebibou Thanks for the input! Can you open a PR with some suggestions? The command structure is listed in the Readme, but I'm happy to improve it to make any part of it clearer.

**Comment by richburdon** [comment]
Hi @fernando-mc I'll open a PR, but am also confused, so if I describe the confusion here and you can explain, I'll send a PR for an updated README.

1). You don't mention any endpoint (i.e., no "functions" section in the config) so how do you "visit the website". The deploy output and sls info don't tell me anything.

2). Use case: I'm using aws-serverless-express and was hoping to use serverless-finch to "host" static files that I can reference from, say, and express template. Again, how? Are/where are the files accessible.

Thanks!

**Comment by richburdon** [comment]
@mebibou I think you have to visit your AWS Console and go to the S3 section. You'll then see your bucket and can access your files here:

https://s3.amazonaws.com/YOUR_BUCKET_NAME/YOUR_FILE

**Comment by fernando-mc** [comment]
@mebibou rereading this today and I'm a bit confused by what you mean by lacking `bin`. This plugin deploys static website assests to an S3 bucket and configures that bucket as a static site. By default this is an AWS S3 static site with an AWS static site domain like `some-bucket-you-deploy-to.s3-website-us-east-1.amazonaws.com`

I'd like in the future to enable it to deploy to custom domains too, but I haven't had the time to add that functionality yet.

@richburdon Thanks for letting me know that it isn't outputting the location it's deploying to. I previously made changes to output the deploy locations, sounds like this isn't working for you? It should be doing this - https://github.com/fernando-mc/serverless-finch/blob/master/index.js#L253 but it's totally possible I made some error when pushing the package. 

Basically after running `serverless client deploy` you should see a message saying where the site should be deployed at (currently just an AWS static site url)

_1). You don't mention any endpoint (i.e., no "functions" section in the config) so how do you "visit the website". The deploy output and sls info don't tell me anything._

Technically this plugin doesn't require any functions to be configured. It makes use of AWS S3 static site hosting. If the logs aren't showing the website URL that's what we need to fix I think. Maybe to also add clarity that this deploys static site files to an S3 bucket and hosts them there (not via Lambda or anything). 

_2). Use case: I'm using aws-serverless-express and was hoping to use serverless-finch to "host" static files that I can reference from, say, and express template. Again, how? Are/where are the files accessible._

This plugin pushes files to an S3 bucket and configures them to be publicly available to the web. You could theoretically reference them from the url they are at after deployment but that might not be exactly what you want.

@mebibou if you have further questions please let me know. 

@richburdon if you can screenshot the output of your terminal/prompt after running serverless client deploy that would be very helpful for debugging/fixing the issue with not outputting the url it is deployed to.

**Comment by richburdon** [comment]
@fernando-mc thanks for the detailed response.

Sorry, my mistake, the URL is in fact in the output. I hadn't noticed it the first time and was looking for a record of it in `sls info`. I'm new to serverless is my excuse :).

Re templates, I've since discovered that I can use the `copy-webpack-plugin` webpack plugin to declare local directories that will be packaged so that these files are accessible by the lambda function.

Thanks again.

**Comment by fernando-mc** [comment]
@mebibou Can you please add more information about what you tried and what was unclear about the functionality here? I'll do my best to address it.

@richburdon Sounds good! Glad you found a solution. Please feel free to come back anytime and help build additional functionality you might like to see.

**Comment by mebibou** [comment]
yes sorry I realized afterwards what this plugin was really about, and that it had to be used with `serverless`, which I never used before so I was really confused at first. Thanks for your help
