### ISSUE TITLE
Control is not return back when hooking with other serverless plugin

### ISSUE THREAD

**Issue by tahir-mm** [fernando-mc/serverless-finch#52]
This is a:

* Bug report

---

### Expected behaviour

When using serverless-finch plugin with other serverless plugin (in our scenario custom build plugin) using hooks, serverless-finch not returning control back, due this we can not complete our other hooks which we want to execute after serverless-finch.

### Actual behavior
serverless-finch plugin should return control back if we are using this with other serverless plugin.

### Proposed implementation deatils (optional)
 Just introduce `return` statement in following index.js file section.
`this.hooks = {
      'client:client': () => {
        serverless.cli.log(this.commands.client.usage);
      },
      'client:deploy:deploy': () => {
        return this._processDeployment();
      },
      'client:remove:remove': () => {
        return this._removeDeployedResources();
      }
    };`
  
It will be much appreciated if @fernando-mc can fixed and published. Thanks

**Comment by fernando-mc** [comment]
@tahir-mm Thanks for the bug report! Can you please open a PR for the proposed fix so I can review and merge it? I rely on community PRs to make updates as there are a lot of proposed fixes/improvements. I'll assign this issue to you for the moment until that PR is created and I or another maintainer can review and merge it.

In the meantime, if this was working in a previous version can you temporarily fall back to that?

**Comment by tahir-mm** [comment]
@fernando-mc I am unable to push my code because of permission error, please guide me how to push code.
I have created a branch from master and when I pushed its giving me permission error.

**Comment by tahir-mm** [comment]
@fernando-mc I have created a PR, please review it. Thanks

**Comment by linusmarco** [comment]
@tahir-mm You cannot push directly to the main repository. This makes sure that we can review all changes before incorporating them into the code base. The standard practice for contributing a change to a github repo is to create a fork on your own account, branch off of master on the fork, push, and then open a pull request. You can find instructions for how to do this here:

https://gist.github.com/Chaser324/ce0505fbed06b947d962 

Let me know if you have questions.

**Comment by linusmarco** [comment]
Whoops, looks like you figured it out on your own. Great!
