### ISSUE TITLE
get bucket id for CF code?

### ISSUE THREAD

**Issue by bebbi** [fernando-mc/serverless-finch#57]
This is a:

Question

With my previous manual S3 bucket + CF distribution I had a line under `CF_resource/Properties/DistributionConfig/Origins`:

    - DomainName:
      'Fn::GetAtt': [ WebAppS3Bucket, DomainName ]

What's the best way to replace that with sls-finch plugin?

Thanks!

**Comment by fernando-mc** [comment]
@bebbi not sure we have a good solution for Cloudfront distributions at the moment. Please feel free to put in a PR for additional functionality!

We currently have a request for something like this here - #40
