### ISSUE TITLE
Not Recognizing Pseudo Parameter

### ISSUE THREAD

**Issue by wordyallen** [fernando-mc/serverless-finch#66]
This is a:

* [x] Feature request or change
* [] Bug report

---

For bug reports:

### Expected behavior
<br/>
<br/>
<br/>

Using `serverless-pseudo-parameters` pluging

```
custom:
  client:
    bucketName: ${self:provider.stage}-admin-dashboard-#{AWS::AccountId}
```

should create a bucket with name: `dev-admin-dashboard-0123456`

### Actual behavior
<br/>
<br/>

Tries to create buck with name: 

`dev-admin-dashboard-#{AWS::AccountId}`

and fails.

### Steps to reproduce

* **Operating system:**
* **serverless-finch version:**
* `serverless.yml` **that produces bug:**
* **Command that produces bug:**
* **Other details:**

---

For feature requests or changes:

**Comment by fernando-mc** [comment]
@wordyallen looks like a cool plugin - I've never used it before. Thanks for bringing this to our attention!

Are you convinced this is an issue with Serverless Finch or it it possible serverless-pseudo-parameters doesn't support the parameters for other plugins?

If you isolate the issue and open a PR I'm happy to merge a fix!

**Comment by souravs-2pirad** [comment]
Facing same issue. Please fix.

**Comment by fernando-mc** [comment]
Hi @souravs-2pirad, happy to review any PRs you have that might fix the issue, cheers!

**Comment by mikejpeters** [comment]
I'm closing this issue because serverless-pseudo-parameters is now [deprecated](https://github.com/svdgraaf/serverless-pseudo-parameters#deprecated) (it's functionality is provided is in Serverless framework). Please open a new issue if you still run into any issues.
