### ISSUE TITLE
Add support for eu-north-1 (Stockholm)

### ISSUE THREAD

**Issue by malnor** [fernando-mc/serverless-finch#72]
It seems like lib/resources/awsRegionUrls.json should include eu-north-1, maybe there is something more missing.

**Comment by fernando-mc** [comment]
@malnor Nice! Yep looks like that got released a month ago and we never added it. 

Do you mind putting in the PR?

**Comment by fernando-mc** [comment]
@malnor Want to add this in?

**Comment by ash211** [comment]
Done in https://github.com/fernando-mc/serverless-finch/pull/101.  This can be closed.
