### ISSUE TITLE
Specify key prefix

### ISSUE THREAD

**Issue by EgidioCaprino** [fernando-mc/serverless-finch#73]
This is a:

* [x] Feature request or change
* [] Bug report

---

For feature requests or changes:

### Current behavior (if any)
Files can only be uploaded at the root level of the S3 bucket.

### Proposed behavior
An option to specify a key prefix so files could be uploaded in a subfolder.

### Justification
I'm not using this plugin for hosting a website but rather for hosting static assets of a Next.js application. If I could specify a `static/` key prefix then the deployment would match Next.js file naming convention.

**Comment by fernando-mc** [comment]
@EgidioCaprino I think this could be a good suggestion. I assume the expectation for that sort of deployment would still be public accessibility?

I'm open to PRs that add this functionality so if you or others are interested please go for it (just claim it here so we can keep track of it)

**Comment by fernando-mc** [comment]
This is solved by #76 and will be included in the next release.

**Comment by fernando-mc** [comment]
@EgidioCaprino thanks for the suggestion!
