### ISSUE TITLE
Feature request: Support serverless offline

### ISSUE THREAD

**Issue by NoamKoKo** [fernando-mc/serverless-finch#78]
### Current behavior:
Running serverless offline (using the plugin `serverless-offline`) does not host the static files.

### Proposed behavior:
Running serverless offline will host it in such manner that requesting `localhost:3000` will return the `index.html` file.

**Comment by fernando-mc** [comment]
@NoamKoKo Correct me if I'm wrong but maybe this should be a request for the serverless-offline plugin?

**Comment by NoamKoKo** [comment]
You might be right, I am quite new to both Serverless framework and Github.
Is it something you can't control?
Because then we have no choice but request it from the serverless-offline plugin.

**Comment by fernando-mc** [comment]
@NoamKoKo No worries. While we could *theoretically* add a feature to run a local server that serves the content locally it isn't really in the scope of the `serverless-finch` plugin. 

I think this would make more sense to put in `serverless-offline` as I think the purpose of that plugin will fit better with your request. You can open a feature request on that plugin here: https://github.com/dherault/serverless-offline/issues
