### ISSUE TITLE
Using keyPrefix results in an XML not well-formed or not validated error

### ISSUE THREAD

**Issue by victormacko** [fernando-mc/serverless-finch#85]
This is a:

* X Bug report

---

For bug reports:

### Expected behavior
Using the 'keyPrefix: ...' param, i'm expecting the dirs and files in the bundles dir to appear in the bucket, underneath within the 'bundles' prefix (configured below) (eg. mybucket/bundles/abcd ... etc)
Eg;
custom:
  client:
    bucketName: mybucket
    distributionFolder: public/bundles
    keyPrefix: bundles

### Actual behavior

$ sls client deploy --no-confirm

When deploying, it comes up with the following error;
Serverless: This deployment will:
Serverless: - Upload all files from 'public/bundles' to bucket 'mybucket'
Serverless: - Set (and overwrite) bucket 'mybucket' configuration
Serverless: - Set (and overwrite) bucket 'mybucket' bucket policy
Serverless: - Set (and overwrite) bucket 'mybucket' CORS policy
Serverless: Looking for bucket...
Serverless: Bucket found...
Serverless: Deleting all objects from bucket...
 
  Serverless Error ---------------------------------------
 
  ServerlessError: The XML you provided was not well-formed or did not validate against our published schema
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              6.14.3
     Serverless Version:        1.49.0
     Enterprise Plugin Version: 1.3.5
     Platform SDK Version:      2.1.0

### Steps to reproduce

* **Operating system:** linux
* **serverless-finch version:** serverless-finch@2.4.2
* `serverless.yml` **that produces bug:**

custom:
  client:
    bucketName: mybucket
    distributionFolder: public/bundles
    keyPrefix: bundles
  scripts:
    hooks:
      'deploy:createDeploymentArtifacts': sls client deploy --no-confirm

plugins:
  - ./vendor/bref/bref
  - serverless-plugin-scripts
  - serverless-finch

... (functions omitted) ...

* **Command that produces bug:** sls client deploy --no-confirm
* **Other details:**
I've tried multiple ways and the only different seems to be the 'keyPrefix' to either make that error come up (by adding the keyPrefix), or go away (removing the keyPrefix)

**Comment by fernando-mc** [comment]
@linusmarco got any time to take a look at this?

**Comment by damien-monni** [comment]
I had the same problem. It seems that it happens when the bucket already exists without the keyPrefix folder created yet. But I have not time to look deeper. I deleted the entire bucket, run serverless `client deploy...` and it worked.

**Comment by josephnle** [comment]
It seems that the issue might be with the content deletion. I can get around this with `--no-delete-contents`.
