### ISSUE TITLE
Deep upload paths specified with keyPrefix get resolved incorrectly

### ISSUE THREAD

**Issue by ol-ko** [fernando-mc/serverless-finch#86]
This is a:

* [ ] Feature request or change
* [x] Bug report

### Expected behavior

Specifying a deep path in a `keyPrefix` option (e.g. `'a/b'`) results in uploading files to `<s3-bucket-base-url>/a/b` folder.

### Actual behavior

Currently when a deep path is specified via`keyPrefix` (e.g. `'a/b'`) files get uploaded to a folder with the name, consisting of a comma-separated parts of the specified path (like `'a,b'`). 

### Steps to reproduce

* **Operating system:** macOS Mojave 
* **serverless-finch version:** 2.4.2
* `serverless.yml` **that produces bug:** 

Here's the chunk of the serverless.yml file related to the behaviour:
```
...
plugins:
  - serverless-finch

custom:
  client:
    bucketName: some-bucket-name
    distributionFolder: dist/client/compressed
    keyPrefix: a/b
...
```

* **Command that produces bug:** `serverless client deploy`

* **Other details:**

The root of the problem seems to be here:
https://github.com/fernando-mc/serverless-finch/blob/master/lib/upload.js#L94

We are adding `prefix` (which is an array) as an element of `fileKey` array. Elements of `fileKey` array later get joined with a `/` separator. (https://github.com/fernando-mc/serverless-finch/blob/master/lib/upload.js#L98) 

When `.join()` is run on a nested array, it converts elements of that array to strings, which results in an undesirable effect with commas in our case: 
```[['a', 'b'], 'c', 'd'].join('/') // results in 'a,b/c/d'```

Here's a codepen illustrating this: https://codepen.io/_olko/pen/bGbpboo

Will create a pull request.

**Comment by ol-ko** [comment]
Here's a PR with the suggested fix: https://github.com/fernando-mc/serverless-finch/pull/87

**Comment by fernando-mc** [comment]
Excellent. Thanks so much for the explanation/demonstration and PR. I'll push this in the next version!

**Comment by ahderman** [comment]
@fernando-mc Do you have an estimated date for the next release that will include this change?

**Comment by fernando-mc** [comment]
Just pushed a new version @ahderman

**Comment by fernando-mc** [comment]
Changes should be live in v2.4.3.
