### ISSUE TITLE
Use custom cors configuration

### ISSUE THREAD

**Issue by hequ** [fernando-mc/serverless-finch#88]
This is a:

* [x] Feature request or change
* [ ] Bug report

### Current behavior (if any)

Serverless-finch will override s3 bucket CORS configuration or it does not touch the configuration at all.

### Proposed behavior

User can provide custom CORS configuration for the bucket the same way as `bucketPolicyFile` works.

### Proposed implementation details (optional)

Add new configuration setting `bucketCorsConfiguration` which would be the path to cors configuration .json file.

I have a proposal about how this could work if this is something that could be considered to be added in the future.

### Justification

The project I'm currently working needs special cors configuration for the SPA to work correctly. We use serverless-finch but we have had to disable the cors configuration override since it would break our deployment every time. It would be great to manage the CORS settings with finch as well.

**Comment by fernando-mc** [comment]
If you think this is a use case not currently covered well enough by:

--no-config-change and the `bucketPolicyFile` option I'm open to a PR @hequ.

**Comment by hequ** [comment]
> If you think this is a use case not currently covered well enough by:
> 
> --no-config-change and the `bucketPolicyFile` option I'm open to a PR @hequ.

Sorry, I have not (for some reason) seen this PR until now. I'll see if I can take some time to submit a PR for this. :)

**Comment by fernando-mc** [comment]
@hequ Awesome! Thank you! As long as you take a look at those two options and confirm for me that it'll be adding new functionality here I'm 100% open to this. Sounds like a good addition from first glance that I don't think we have in the plugin.

**Comment by gipsh** [comment]
#103
