### ISSUE TITLE
`client remove` functionality

### ISSUE THREAD

**Issue by redroot** [fernando-mc/serverless-finch#9]
I was wondering what you thought about adding `remove` as a CLI option, similar to the `serverless remove` command. In this case it would empty the bucket and delete it. I'm happy to work on the PR myself but wanted to make sure it wasn't a feature you were against?

**Comment by fernando-mc** [comment]
Sounds like a good idea. I can’t think of many drawbacks other than
accidental site nuking but that’s the case with many tools. Go for it!

**Comment by fernando-mc** [comment]
@redroot I still can't think of any reason not to. I've added this as an enhancement.

**Comment by fernando-mc** [comment]
@redroot This looks pretty solid. I'll test this tonight along with a few other things and try to get it all merged and published.

I'll also add you as a contributor and update the readme with the new functionality.

**Comment by fernando-mc** [comment]
Added with [this PR](https://github.com/fernando-mc/serverless-finch/pull/10) from @redroot
