### ISSUE TITLE
Switch upload from S3 putObject to S3 upload

### ISSUE THREAD

**Issue by tgallacher** [fernando-mc/serverless-finch#94]
This is a:

* [x] Feature request or change
* [ ] Bug report

---

For feature requests or changes:

### Current behavior (if any)

Although we are leveraging Node's async I/O via `Promise.all` call, as we use AWS S3's `putObject` call, files are processed serially on S3's end.

### Proposed behavior

Switch to use AWS' S3 "[managed upload](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3/ManagedUpload.html)" stream, which parallelises the upload and ingress into the bucket

### Proposed implementation details (optional)

After a quick look at the code, I think it should be as simple as changing the S3 method on this line: https://github.com/fernando-mc/serverless-finch/blob/master/lib/upload.js#L83. All other params stay the same. 

There might be some finer details in the return objects etc and how you are handling these, but I can't see anything special yet. So should be relatively simple to try out. 

Happy to give a PR a go and see where we land.

### Justification

This has the opportunity to offer speed improvements. 

Currently, my S3 uploads take around 10 mins to process (even when using AWS's S3 accelerated endpoint).

**Comment by fernando-mc** [comment]
@tgallacher Great suggestion! Please do put in a PR for this, I'd love to be able to include a performance improvement like this in the next version!

**Comment by fernando-mc** [comment]
@tgallacher One main question to determine how we push this out:

This would just change the method of upload to make it faster right? Do you know if there would there be any increase in S3 cost using the different method with your changes?

**Comment by tgallacher** [comment]
Hey @fernando-mc. As far as I can tell this should not impact the upload cost -- unless you opt for the already supported "accelerated S3 endpoint". This would be just a change to the upload method, to support multipart uploads. 

Happily give this a try and let you know. Is there any test coverage areas that you would require for this?

**Comment by tgallacher** [comment]
Ok. I've done some quick initial testing and it isn't as exactly as I original understood it. 

Switching to the `upload` S3 method will be very useful for files that are large (I think the default threshold is > 5MB). In those cases, the `upload` method chunks the file into smaller pieces and uploads them concurrently. 

But for smaller files, it basically defaults to the `putObject` call which you already have. 

I tried playing around with the chunk threshold a bit using a local copy of the plugin and it made a small difference, but not significant enough that I think it warrants the PR. Alternatively, if you think a lot of people using this plugin might have large files then, given the graceful fallback to `putObject` for small files then it might be a worthy update? 

Also, update in terms of cost. There is a potential increase in cost. But this really depends on the size of file. 

Basically, the way the costing works -- from what I can see -- is when a file is large enough to be chunked (and uploaded concurrently), with the default threshold being 5MB, then the `upload` method will do a "_multi-part_" upload with each part / chunk being uploaded in parallel. These parts are uploaded to S3 and then when the final part is uploaded, the parts are "stitched" back together to make the original object. 

S3 has a "charge" to store these chunks/parts. However, when the parts are stitched back together then the parts are deleted and you are only charged for storing the final object; as standard. 


So. Not sure if you think it is worth the change here? Depends on if enough people use this for large files. 


Either way, happy to create the PR if so. 

Some notes on multi-part uploads including pricing: https://docs.aws.amazon.com/AmazonS3/latest/dev/mpuoverview.html

**Comment by fernando-mc** [comment]
@tgallacher thanks for doing the research here! I wouldn't be very worried about the chunked objects costing too much more than the original but if it will only really benefit very large files I'm not sure how much of a performance improvement it would bring? I feel like this plugin is primarily used for static websites and I don't know how many sites will have bigger files.

If you test this and find enough benefit from it yourself then I'm open to a contribution though. As far as I can tell this would only be an improvement.

**Comment by tgallacher** [comment]
Yeah. I agree. I don't believe this is worth the change. I'll close for now. Thanks
