### ISSUE TITLE
Add support for tags

### ISSUE THREAD

**Issue by itsjesseyo** [fernando-mc/serverless-finch#95]
This is a:

* [X] Feature request or change

For feature requests or changes:

### Current behavior (if any)
Currently tags, or stackTags do not propagate to the created s3 bucket.

### Proposed behavior
I'd like the tags tag supported and to update when change similar to how bucketpolicy works

### Proposed implementation details (optional)
Feel free to point me in the direction of  how to do this myself. It's a feature worth adding, though I have never made a serverless plugin before.

### Justification
Most of the companies I have worked for use tags for internal team management and finances via different teams. They follow a pattern that's very easily reusable and programmatic. There's literally a robot that goes off and notifies a  group of people if I fail to create tags on an s3 bucket quickly enough.

**Comment by fernando-mc** [comment]
Hi @itsjesseyo! Thanks for the suggestion, you're welcome to add a PR for this. Would this end up allowing tagging just on the bucket itself or would you expect tags for every object inside of it?

**Comment by itsjesseyo** [comment]
There is a command for tagging  each object, but tagging the bucket would be adequate for most people. If we need object level tagging, I can add that as well.

PR  submitted.

**Comment by fernando-mc** [comment]
Closing because this was added in v2.6.0. Thanks again!
