### ISSUE TITLE
pre and post build commands

### ISSUE THREAD

**Issue by itsjesseyo** [fernando-mc/serverless-finch#97]
This is a:

* [X] Feature request or change

---

For feature requests or changes:

### Current behavior (if any)
There does not currently  seem to be a way to call custom functions before or after a deploy.

### Proposed behavior
I'd like to add the  ability for a developer to  add an array of commands, which will be called before or after the deployment

### Proposed implementation details (optional)
I'd be glad to do the work, and could use advice on whether taking the step of adding new hooks and lifecycle events, or simply stringing the command calls into the .then chain you have. post build commands seem a bit much, but while I'm there the symmetry could be useful for some devops processes - like a slack hook to notify  of deployment

### Justification
I was debating between this plugin and serverless web component. fact is this plugin is further along and a bit more flexible. However, I feel it's missing two "enterprise level" features that are useful for more complex teams and processes. This is the second  of the  two missing features. If you imagine this being run on something like docker jenkins, something to trigger the build process, then something to post build  and  deploy results could be useful.

**Comment by fernando-mc** [comment]
Just commented on the PR, but would this be similar to this plugin: https://github.com/mvila/serverless-plugin-scripts

**Comment by itsjesseyo** [comment]
I answered in the PR.

**Comment by fernando-mc** [comment]
Closing because I closed #98
